package models;
// Generated 02-jun-2020 18:47:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer idproducto;
	private String descripcion;
	private Integer stockactual;
	private Integer stockminimo;
	private Integer pvp;
	private Set ventases = new HashSet(0);

	public Productos() {
	}

	public Productos(String descripcion) {
		this.descripcion = descripcion;
	}

	public Productos(String descripcion, Integer stockactual, Integer stockminimo, Integer pvp, Set ventases) {
		this.descripcion = descripcion;
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.pvp = pvp;
		this.ventases = ventases;
	}

	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStockactual() {
		return this.stockactual;
	}

	public void setStockactual(Integer stockactual) {
		this.stockactual = stockactual;
	}

	public Integer getStockminimo() {
		return this.stockminimo;
	}

	public void setStockminimo(Integer stockminimo) {
		this.stockminimo = stockminimo;
	}

	public Integer getPvp() {
		return this.pvp;
	}

	public void setPvp(Integer pvp) {
		this.pvp = pvp;
	}

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

}
