package models;
// Generated 02-jun-2020 18:47:55 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private int idventa;
	private int clientes;
	private int productos;
	private Date fechaventa;
	private int cantidad;

	public Ventas() {
	}

	public Ventas(int clientes, int productos, Date fechaventa, int cantidad) {
		this.clientes = clientes;
		this.productos = productos;
		this.fechaventa = fechaventa;
		this.cantidad = cantidad;
	}

	public Integer getIdventa() {
		return this.idventa;
	}

	public void setIdventa(int idventa) {
		this.idventa = idventa;
	}

	public Integer getClientes() {
		return this.clientes;
	}

	public void setClientes(int clientes) {
		this.clientes = clientes;
	}

	public Integer getProductos() {
		return this.productos;
	}

	public void setProductos(int productos) {
		this.productos = productos;
	}

	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
